from fastapi import APIRouter, HTTPException
from pydantic import BaseModel, Field
from backend import bhashini

router = APIRouter()


@router.get("/api/languages", tags=["Multilingual"])
def languages():
    from backend.synthesizer import EXTRA_LANGS
    langs = [{"code": "en", "name": "English"}, {"code": "hi", "name": "Hindi"}] + [{"code": k, "name": v[0]} for k, v in EXTRA_LANGS.items()]
    return {"languages": langs, "bhashini_configured": bhashini.configured(),
            "note": "Non-English answers are generated by the Groq LLM from English sources. Bhashini translation is optional."}


class TranslateRequest(BaseModel):
    text: str = Field(..., min_length=1, max_length=6000)
    target: str = Field(..., min_length=2, max_length=5)


@router.post("/api/translate", tags=["Multilingual"])
def translate(payload: TranslateRequest):
    if not bhashini.configured():
        raise HTTPException(status_code=503, detail="Bhashini is not configured (set BHASHINI_USER_ID and BHASHINI_API_KEY).")
    out = bhashini.translate(payload.text, payload.target)
    if not out:
        raise HTTPException(status_code=502, detail="Bhashini translation failed. Try again or use the Groq answer language option.")
    return {"translation": out, "engine": "bhashini"}
