"""
Safety Guardrails and Abstention Hardening Module for SAKTI.
Implements:
1. Prompt Injection Protection (Jailbreak / System Prompt Override detection)
2. Out-of-Scope Query Rejection (Filters queries unrelated to Ayurveda/IPR/Drug laws)
3. Input Sanitization (Strips adversarial control tags and jailbreak delimiters)
4. Mandatory Legal Disclaimer Enforcer
5. Safe Error Fallbacks (Guarantees zero leakage of sensitive keys or crashes)
"""

import re
from typing import Tuple, Optional
from pydantic import BaseModel

MANDATORY_LEGAL_DISCLAIMER = (
    "LEGAL DISCLAIMER: This response is generated by SAKTI for informational, educational, and Smart India Hackathon "
    "research purposes only. It is grounded in curated statutory texts but does not constitute formal legal advice, "
    "patent prosecution opinion, or attorney-client counsel. Consult a registered patent agent or legal counsel for binding determinations."
)

MANDATORY_LEGAL_DISCLAIMER_HI = (
    "कानूनी अस्वीकरण (LEGAL DISCLAIMER): यह उत्तर SAKTI द्वारा केवल सूचनात्मक, शैक्षणिक और स्मार्ट इंडिया हैकथॉन "
    "शोध उद्देश्यों के लिए तैयार किया गया है। यह आधिकारिक सांविधिक प्रावधानों पर आधारित है परंतु यह कोई औपचारिक कानूनी सलाह, "
    "पेटेंट अभियोजन राय या विधिक परामर्श नहीं है। बाध्यकारी निर्णयों के लिए कृपया पंजीकृत पेटेंट एजेंट या कानूनी सलाहकार से परामर्श लें।"
)

# Common Prompt Injection & Jailbreak patterns
INJECTION_PATTERNS = [
    r"(?i)ignore\s+(all\s+)?(previous|prior|above)\s+(instructions|directives|prompts)",
    r"(?i)disregard\s+(all\s+)?(previous|prior|above)\s+(instructions|directives|prompts)",
    r"(?i)you\s+are\s+now\s+(in\s+developer\s+mode|dan|unconstrained|jailbroken)",
    r"(?i)(system\s+prompt|system\s+instructions|system\s+parameters)",
    r"(?i)(override|bypass)\s+(all\s+)?(rules|safety|guardrails|instructions|constraints)",
    r"(?i)reveal\s+(.*)?(instructions|prompt|api\s*key|parameters?|credentials)",
    r"(?i)(show|output|print|give)\s+(me\s+)?(your\s+)?(system\s+)?(prompt|instructions)",
    r"(?i)bypass\s+(all\s+)?(safety|guardrails|rules)",
    r"(?i)pretend\s+you\s+have\s+no\s+(rules|restrictions|guidelines)",
    r"(?i)forget\s+(your\s+)?(instructions|guidelines|disclaimer)",
    r"(?i)api\s*(key|secret|token)\s*(leak|reveal|print)"
]

ADVERSARIAL_TAGS = [
    "[system]", "<<sys>>", "---begin system prompt---",
    "<|im_start|>", "<|im_end|>", "<system>"
]

# Core domain relevance indicators (Ayurveda, IPR, Drug Laws, ABS, Botany - English + Hindi/Devanagari)
AYUSH_IPR_KEYWORDS = [
    "patent", "ipr", "intellectual property", "trademark", "trade secret",
    "ayush", "ayurved", "ayurveda", "siddha", "unani", "herbal", "herb", "botanical",
    "formulation", "churna", "kwath", "asava", "taila", "bhasma", "ghrita",
    "turmeric", "haldi", "curcumin", "ginger", "honey", "ashwagandha", "neem",
    "tulsi", "pepper", "bacopa", "brahmi", "plant", "medicine", "drug",
    "biodiversity", "abs", "nba", "sbb", "national biodiversity authority",
    "traditional knowledge", "tkdl", "prior art", "geographical indication",
    "cosmetic", "food", "nutraceutical", "ayurveda aahar", "fssai",
    "cdsco", "license", "licensing", "first schedule", "phytopharmaceutical",
    "section 3(p)", "section 3(e)", "section 3(d)", "section 6", "wipo",
    "nagoya", "gratk", "pct", "trips", "regulations", "statute", "rule",
    # Hindi / Devanagari domain markers
    "हल्दी", "काली मिर्च", "अश्वगंधा", "नीम", "तुलसी", "आयुर्वेद", "पेटेंट",
    "पारंपरिक ज्ञान", "जैव विविधता", "एनबीए", "दवा", "औषधि", "धारा", "ट्रेडमार्क",
    "भौगोलिक उपदर्शन", "अनुज्ञा", "लाइसेंस"
]

class GuardrailResult(BaseModel):
    is_safe: bool
    status: str  # "PASSED" | "INJECTION_BLOCKED" | "OUT_OF_SCOPE"
    rejection_message: Optional[str] = None
    sanitized_query: str

class SafetyGuardrails:
    @classmethod
    def sanitize(cls, text: str) -> str:
        """Strips control tags, excessive whitespace, and common prompt injection wrappers."""
        cleaned = re.sub(r"[\r\t\v\f]", " ", text)
        cleaned = re.sub(r"\s+", " ", cleaned).strip()
        for tag in ADVERSARIAL_TAGS:
            cleaned = re.sub(re.escape(tag), "", cleaned, flags=re.IGNORECASE)
        return cleaned

    @classmethod
    def inspect(cls, query: str) -> GuardrailResult:
        """
        Runs comprehensive safety checks:
        1. Checks for prompt injection & adversarial jailbreak attempts
        2. Checks for domain scope relevance
        """
        raw_lower = query.lower()

        # 1A. Check for explicit adversarial jailbreak delimiters in raw query
        for tag in ADVERSARIAL_TAGS:
            if tag in raw_lower:
                return GuardrailResult(
                    is_safe=False,
                    status="INJECTION_BLOCKED",
                    rejection_message=(
                        "SECURITY GUARDRAIL TRIGGERED: Prompt manipulation or instruction override attempt detected. "
                        "SAKTI strictly adheres to grounded statutory legal analysis and does not permit system instruction overrides."
                    ),
                    sanitized_query=cls.sanitize(query)
                )

        sanitized = cls.sanitize(query)

        # 1B. Check for semantic prompt injection patterns
        for pattern in INJECTION_PATTERNS:
            if re.search(pattern, query) or re.search(pattern, sanitized):
                return GuardrailResult(
                    is_safe=False,
                    status="INJECTION_BLOCKED",
                    rejection_message=(
                        "SECURITY GUARDRAIL TRIGGERED: Prompt manipulation or instruction override attempt detected. "
                        "SAKTI strictly adheres to grounded statutory legal analysis and does not permit system instruction overrides."
                    ),
                    sanitized_query=sanitized
                )

        # 2. Out-of-Scope Query Filter
        # Check if the query has at least one domain relevance marker
        query_lower = sanitized.lower()
        has_domain_keyword = any(kw in query_lower for kw in AYUSH_IPR_KEYWORDS)

        # If length is tiny or completely unrelated (e.g. math problem, crypto, recipe for pizza)
        if not has_domain_keyword and len(sanitized.split()) >= 4:
            # Check for blatantly unrelated domains
            unrelated_indicators = [
                "crypto", "bitcoin", "solidity", "ethereum", "blockchain",
                "python script", "write code", "fix bug", "stock price",
                "movie", "song", "lyrics", "cricket", "football",
                "nuclear", "weapon", "bomb", "hack", "bypass password"
            ]
            if any(un in query_lower for un in unrelated_indicators):
                return GuardrailResult(
                    is_safe=False,
                    status="OUT_OF_SCOPE",
                    rejection_message=(
                        "OUT-OF-SCOPE INQUIRY: SAKTI specializes exclusively in Ayurvedic Intellectual Property Rights (IPR), "
                        "Access & Benefit Sharing (ABS), traditional knowledge protection, and drug/cosmetic regulations. "
                        "Your inquiry appears to fall outside this statutory domain. "
                        "Please submit a question related to Ayurvedic formulations, patentability, NBA compliance, or regulatory frameworks."
                    ),
                    sanitized_query=sanitized
                )

        return GuardrailResult(
            is_safe=True,
            status="PASSED",
            sanitized_query=sanitized
        )

guardrails = SafetyGuardrails()
