"""
Grounded Synthesis and Citation Formatter for SAKTI.
Connects the local dense FAISS retrieval engine with Groq API to generate:
- Evidence-grounded answers strictly based on retrieved statutory text
- Verified source citations with official government URLs
- Confidence scoring (High / Medium / Low)
- Safe abstention mechanism when evidence is insufficient
- Post-synthesis citation verification against corpus IDs
"""

import re
import time
import logging
from typing import List, Dict, Any, Optional
from pydantic import BaseModel, Field
from openai import OpenAI

from backend.config import settings
from backend.vector_store import vector_store, RetrievalResult
from backend.corpus_loader import corpus_store
from backend.audit import log_event
from backend.guardrails import guardrails, MANDATORY_LEGAL_DISCLAIMER, MANDATORY_LEGAL_DISCLAIMER_HI

GROQ_MODEL = settings.GROQ_MODEL  # e.g. "openai/gpt-oss-120b"

ABSTENTION_THRESHOLD = settings.ABSTENTION_THRESHOLD  # Score below which SAKTI safely abstains (calibrate via scripts/run_eval.py)

class CitationItem(BaseModel):
    id: str
    jurisdiction: str
    statute: str
    section_rule: str
    authority: str
    official_url: str
    title: str
    relevance_score: float
    verification_status: Optional[str] = None
    last_verified: Optional[str] = None
    cited_in_answer: bool = True

class SynthesisResponse(BaseModel):
    query: str
    jurisdiction: str
    answer: str
    confidence: str  # "High" | "Medium" | "Low"
    is_abstained: bool
    citations: List[CitationItem]
    disclaimer: str
    language: str = "en"
    retrieval_mode: str = "none"
    citation_check: str = "n/a"
    unverified_citation_ids: List[str] = Field(default_factory=list)
    generation_mode: str = "none"
    confidence_reason: Optional[str] = None

# Additional Indian languages: answers are generated by the LLM; Source IDs, statute names and URLs stay in English.
EXTRA_LANGS = {
    "gu": ("Gujarati", "અસ્વીકરણ: આ માહિતી છે, કાનૂની સલાહ નથી. બંધનકર્તા નિર્ણય માટે નોંધાયેલા પેટન્ટ એજન્ટ કે વકીલની સલાહ લો."),
    "mr": ("Marathi", "अस्वीकरण: ही माहिती आहे, कायदेशीर सल्ला नाही. बंधनकारक निर्णयासाठी नोंदणीकृत पेटंट एजंट किंवा वकिलाचा सल्ला घ्या."),
    "ta": ("Tamil", "மறுப்பு: இது தகவல் மட்டுமே, சட்ட ஆலோசனை அல்ல. உறுதியான முடிவுக்கு பதிவு செய்த காப்புரிமை முகவர் அல்லது வழக்கறிஞரை அணுகவும்."),
    "te": ("Telugu", "నిరాకరణ: ఇది సమాచారం మాత్రమే, న్యాయ సలహా కాదు. తుది నిర్ణయానికి నమోదైన పేటెంట్ ఏజెంట్ లేదా న్యాయవాదిని సంప్రదించండి."),
    "bn": ("Bengali", "দাবিত্যাগ: এটি তথ্য মাত্র, আইনি পরামর্শ নয়। চূড়ান্ত সিদ্ধান্তের জন্য নিবন্ধিত পেটেন্ট এজেন্ট বা আইনজীবীর পরামর্শ নিন।"),
    "kn": ("Kannada", "ಹಕ್ಕುತ್ಯಾಗ: ಇದು ಮಾಹಿತಿ ಮಾತ್ರ, ಕಾನೂನು ಸಲಹೆಯಲ್ಲ. ಅಂತಿಮ ನಿರ್ಧಾರಕ್ಕೆ ನೋಂದಾಯಿತ ಪೇಟೆಂಟ್ ಏಜೆಂಟ್ ಅಥವಾ ವಕೀಲರನ್ನು ಸಂಪರ್ಕಿಸಿ."),
    "ml": ("Malayalam", "നിരാകരണം: ഇത് വിവരം മാത്രമാണ്, നിയമോപദേശമല്ല. അന്തിമ തീരുമാനത്തിന് രജിസ്റ്റർ ചെയ്ത പേറ്റന്റ് ഏജന്റിനെയോ അഭിഭാഷകനെയോ സമീപിക്കുക."),
    "pa": ("Punjabi", "ਬੇਦਾਅਵਾ: ਇਹ ਜਾਣਕਾਰੀ ਹੈ, ਕਾਨੂੰਨੀ ਸਲਾਹ ਨਹੀਂ। ਅੰਤਿਮ ਫ਼ੈਸਲੇ ਲਈ ਰਜਿਸਟਰਡ ਪੇਟੈਂਟ ਏਜੰਟ ਜਾਂ ਵਕੀਲ ਨਾਲ ਸਲਾਹ ਕਰੋ।"),
}


class GroundedSynthesizer:
    def __init__(self, api_key: Optional[str] = None):
        self.api_key = api_key or settings.GROQ_API_KEY
        # Groq uses an OpenAI-compatible API
        self.client = OpenAI(
            api_key=self.api_key,
            base_url="https://api.groq.com/openai/v1",
        ) if self.api_key else None
        self.last_model = None

    def _call_groq(self, prompt: str) -> str:
        """Invokes the Groq LLM with a single user message."""
        if not self.client:
            raise ValueError("GROQ_API_KEY is not configured in environment or .env file.")

        try:
            response = self.client.chat.completions.create(
                model=GROQ_MODEL,
                messages=[{"role": "user", "content": prompt}],
                temperature=0.2,
                max_tokens=4096,
            )
            self.last_model = GROQ_MODEL
            return response.choices[0].message.content.strip()
        except Exception as e:
            raise RuntimeError(f"Groq API call failed: {e}") from e

    def _synthesize(
        self,
        query: str,
        jurisdiction: Optional[str] = "India",
        top_k: int = 4,
        language: Optional[str] = "en"
    ) -> SynthesisResponse:
        """
        Executes grounded retrieval and synthesis with active guardrails and bilingual (EN/HI) support.
        """
        # Determine language preference: explicit "hi" or detected Devanagari script
        is_hindi = (language == "hi") or bool(re.search(r"[\u0900-\u097F]", query))
        target_lang = "hi" if is_hindi else "en"
        disclaimer_text = MANDATORY_LEGAL_DISCLAIMER_HI if target_lang == "hi" else MANDATORY_LEGAL_DISCLAIMER
        extra_lang = language if (language in EXTRA_LANGS and target_lang == "en") else None
        if extra_lang:
            disclaimer_text = disclaimer_text + "\n" + EXTRA_LANGS[extra_lang][1]

        # Step 0: Safety Guardrail Inspection (Prompt Injection & Scope Filter)
        guard = guardrails.inspect(query)
        if not guard.is_safe:
            rejection_text = guard.rejection_message or "Request blocked by safety guardrails."
            if target_lang == "hi":
                rejection_text = (
                    "सुरक्षा जांच (SAFETY GUARDRAIL): आपका अनुरोध सुरक्षा नीतियों अथवा प्रणाली सीमाओं के कारण रोका गया। "
                    "SAKTI केवल आयुष बौद्धिक संपदा, जैव विविधता (ABS) और औषधि नियमों से संबंधित प्रामाणिक कानूनी विश्लेषण प्रदान करता है।"
                )
            return SynthesisResponse(
                query=guard.sanitized_query,
                jurisdiction=jurisdiction or "All",
                answer=rejection_text,
                confidence="Low",
                is_abstained=True,
                citations=[],
                disclaimer=disclaimer_text,
                language=target_lang,
                confidence_reason="Request blocked by safety guardrails."
            )

        sanitized_query = guard.sanitized_query

        # Step 1: Local Vector Retrieval
        retrieved_docs: List[RetrievalResult] = vector_store.search(
            query=sanitized_query,
            top_k=top_k,
            jurisdiction=jurisdiction
        )

        retrieval_mode = getattr(vector_store, "last_mode", "dense")

        # Step 2: Safe Abstention Gate
        top_score = retrieved_docs[0].score if retrieved_docs else 0.0
        if not retrieved_docs or top_score < ABSTENTION_THRESHOLD:
            abstention_msg = (
                "सुरक्षित परिहार (SAFE ABSTENTION): SAKTI कानूनी निश्चितता के साथ उत्तर देने के लिए ज्ञानकोष में पर्याप्त आधिकारिक सांविधिक प्रावधान "
                f"पहचानने में असमर्थ रहा (संबद्धता स्कोर {top_score:.2f}, न्यूनतम सीमा {ABSTENTION_THRESHOLD})।\n\n"
                "कानूनी भ्रम (hallucination) से बचने के लिए, प्रणाली अनुमानित सलाह देने से परहेज करती है। कृपया अपने प्रश्न को और स्पष्ट करें या आधिकारिक आयुष/आईपी इंडिया पोर्टल्स से संपर्क करें।"
                if target_lang == "hi" else (
                    "SAFE ABSTENTION: SAKTI could not identify sufficient authoritative statutory provisions "
                    f"in the curated knowledge base to answer this query with legal certainty (relevance score {top_score:.2f} "
                    f"below threshold {ABSTENTION_THRESHOLD}).\n\n"
                    "To prevent legal hallucination, the system abstains from generating speculative advice. "
                    "Please refine your query or consult official AYUSH/IP India portals."
                )
            )
            return SynthesisResponse(
                query=query,
                jurisdiction=jurisdiction or "All",
                answer=abstention_msg,
                confidence="Low",
                is_abstained=True,
                citations=[],
                disclaimer=disclaimer_text,
                language=target_lang,
                retrieval_mode=retrieval_mode,
                confidence_reason=f"Top score {top_score:.2f} below threshold {ABSTENTION_THRESHOLD} ({retrieval_mode} retrieval)."
            )

        # Step 3: Context Assembly
        context_blocks = []
        doc_map: Dict[str, RetrievalResult] = {}
        for i, doc in enumerate(retrieved_docs):
            doc_map[doc.id] = doc
            context_blocks.append(
                f"--- SOURCE [{i+1}] ---\n"
                f"ID: {doc.id}\n"
                f"Statute: {doc.statute}\n"
                f"Section/Rule: {doc.section_rule}\n"
                f"Title: {doc.title}\n"
                f"Authority: {doc.authority}\n"
                f"Official URL: {doc.official_url}\n"
                f"Curated summary of the provision (may include commentary; not verbatim statutory text):\n{doc.content}\n"
            )

        context_str = "\n".join(context_blocks)

        bilingual_instructions = ""
        if target_lang == "hi":
            bilingual_instructions = f"""
9. BILINGUAL HINDI OUTPUT REQUIREMENTS:
   - Provide your complete analysis in clear, natural, and formal Hindi (Devanagari script).
   - STRICT LEGAL CITATION RULE: Strictly preserve the exact English statutory names, sections, rules, and Source IDs in standard dual/formal format:
     * e.g., 'पेटेंट अधिनियम, 1970 (Patents Act, 1970) की धारा 3(p)' or 'Section 3(p) of the Patents Act, 1970'
     * e.g., 'जैविक विविधता अधिनियम, 2002 (Biological Diversity Act, 2002) की धारा 6'
     * Always retain the exact Source ID in brackets, e.g. `[{retrieved_docs[0].id}]`.
     * Official URLs must remain completely untouched in English.
   - Use standard Hindi headings:
     * ## सारांश (Executive Summary)
     * ## लागू सांविधिक प्रावधान एवं कानूनी विश्लेषण (Applicable Legal Provisions & Statutory Analysis)
     * ## रणनीतिक मार्गदर्शन एवं आगामी कदम (Strategic Guidance & Next Steps)
     * ## निष्कर्ष (Bottom Line Takeaway)
   - Note that official statutory authoritative texts are published in the Official Gazette (राजपत्र) in Hindi and English under the Constitution of India and the Official Languages Act, 1963.
   - Use judicial balance and qualified phrasing (e.g., 'पेटेंट अधिनियम की धारा 3(p) के तहत गंभीर सांविधिक आपत्तियों का सामना करना पड़ सकता है' rather than categorical statements).
"""

        if extra_lang:
            bilingual_instructions += (
                f"\n9. OUTPUT LANGUAGE: Write the entire answer in {EXTRA_LANGS[extra_lang][0]} (native script). "
                "Keep statute names, section numbers, Source IDs in brackets and URLs exactly as in the context (English). "
                "Keep the same standard Markdown headings translated. Do not add facts beyond the context.\n"
            )

        prompt = f"""You are SAKTI, an expert AI legal assistant for Ayurveda Intellectual Property Rights (IPR), Access and Benefit Sharing (ABS), and drug regulations for the Smart India Hackathon.

JURISDICTION FILTER APPLIED: {jurisdiction or 'All'}

AUTHORITATIVE LEGAL CONTEXT (GROUND TRUTH):
{context_str}

USER QUERY:
{query}

INSTRUCTIONS FOR GENERATION:
1. Answer the question AUTHORITATIVELY and COMPREHENSIVELY using ONLY the legal context provided above.
2. For EVERY legal statement, objection, or requirement, explicitly cite the statute and section (e.g., Section 3(p) of the Patents Act, 1970).
3. MANDATORY CITATION REQUIREMENT: For EVERY statute, rule, case precedent, or treaty discussed, you MUST append its exact bracketed Source ID (e.g. `[{retrieved_docs[0].id}]`) in your Summary Answer, in each table row, and in your Strategic Guidance steps. Never mention a legal provision without its bracketed Source ID.
4. Structure your response with the following standard Markdown headings:

   ## Summary Answer
   Provide an executive summary of 2-4 clear, authoritative sentences directly answering the user's inquiry with key conclusions.

   ## Applicable Legal Provisions & Statutory Analysis
   Present the applicable legal provisions and statutory analysis in a clean Markdown table with columns:
   | Issue / Patentability Aspect | Statutory Provision & Authority | How the Provision Applies |
   Ensure every relevant row cites the exact bracketed Source ID (e.g. `[{retrieved_docs[0].id}]`). If a table is unsuitable for this specific query, use clear structured sub-sections.

   ## Strategic Guidance & Next Steps
   Provide concrete, actionable recommendations numbered consecutively:
   1. **Actionable Step Title**: Detailed explanation and operational guidance.
   2. **Actionable Step Title**: Detailed explanation and operational guidance.
   (Use bullet points `* ` for specific sub-tasks or compliance checks under each step).

   ## Bottom Line
   A crisp 1-2 sentence final advisory takeaway summarizing the core legal conclusion.

5. If the context does not contain sufficient statutory authority to answer the query, state 'INSUFFICIENT EVIDENCE' instead of guessing.
6. Do NOT invent sections, rules, or URLs not found in the context.
7. Use ONLY facts stated in the context above. Do not add article numbers, section numbers, dates or fees that are not in the context. Cite sources ONLY with the exact bracketed Source IDs provided (e.g. [IN-PAT-SEC-003P]); never invent an ID.
8. Judicial Balance & Qualified Legal Phrasing:
   - Avoid categorical statements like 'you cannot patent this' or 'it is completely impossible'. Instead, use legally balanced and qualified phrasing such as 'would face significant statutory patentability objections under Section 3(p) and/or Section 3(e)'.
   - Invoke Section 3(p) only when the traditional-knowledge basis is actually supported by the available corpus context.
   - Phrase Section 39 foreign-filing requirements conditionally (it applies specifically to persons resident in India for inventions made in India, requiring an FFL or a 6-week waiting period unless an Indian application was previously filed; it is not a blanket rule for all entities).{bilingual_instructions}

Provide your grounded analysis now:"""

        # Step 4: LLM Generation via Groq
        generation_mode = "llm"
        try:
            raw_answer = self._call_groq(prompt)
        except Exception as e:
            generation_mode = "offline_excerpt"
            logging.getLogger("sakti").warning("LLM unavailable: %s: %s", type(e).__name__, str(e))
            # Fallback synthesis if API is unavailable during demo
            if target_lang == "hi":
                raw_answer = (
                    f"### सांविधिक विश्लेषण (ऑफलाइन ग्राउंडेड मोड)\n\n"
                    f"**{query}** के लिए प्राप्त कानूनी प्रावधान:\n\n"
                    f"1. **{retrieved_docs[0].statute} ({retrieved_docs[0].section_rule})**: {retrieved_docs[0].content[:250]}...\n"
                    f"2. **आधिकारिक प्राधिकरण**: {retrieved_docs[0].authority}\n"
                    f"3. **आधिकारिक संदर्भ**: {retrieved_docs[0].official_url}\n\n"
                    f"*(नोट: LLM सेवा अनुपलब्ध होने के कारण प्रत्यक्ष संदर्भ प्रस्तुत किया गया है)।* "
                )
            else:
                raw_answer = (
                    f"### Statutory Analysis (Offline Grounded Mode)\n\n"
                    f"Based on retrieved legal provisions for **{query}**:\n\n"
                    f"1. **{retrieved_docs[0].statute} ({retrieved_docs[0].section_rule})**: {retrieved_docs[0].content[:250]}...\n"
                    f"2. **Official Authority**: {retrieved_docs[0].authority}\n"
                    f"3. **Official Reference**: {retrieved_docs[0].official_url}\n\n"
                    f"*(Note: LLM service unavailable; grounded context displayed directly).* "
                )

        # Step 4.5: Normalize Unicode punctuation & spaces
        raw_answer = (
            raw_answer
            .replace('\u2010', '-')
            .replace('\u2011', '-')
            .replace('\u2012', '-')
            .replace('\u2013', '-')
            .replace('\u2014', '-')
            .replace('\u2212', '-')
            .replace('\u00a0', ' ')
            .replace('\u202f', ' ')
            .replace('\u2009', ' ')
            .replace('\u200a', ' ')
            .replace('\u200b', '')
        )

        # Step 5: Citation verification against the retrieved set and corpus
        model_abstained = "INSUFFICIENT EVIDENCE" in raw_answer.upper()
        bracket_ids = re.findall(r"\[([A-Z]{2,4}(?:-[A-Z0-9]+)+)\]", raw_answer)
        cited_ids = list(dict.fromkeys(bracket_ids))
        if generation_mode == "offline_excerpt":
            cited_ids = [retrieved_docs[0].id]  # excerpt is taken verbatim from this document
        else:
            # Also catch retrieved IDs mentioned without strict bracket isolation or by specific statutory reference
            for doc in retrieved_docs:
                if doc.id not in cited_ids:
                    if doc.id in raw_answer:
                        cited_ids.append(doc.id)
                    elif doc.section_rule and len(doc.section_rule) > 3 and (doc.section_rule.lower() in raw_answer.lower() or doc.section_rule.lower().replace(" ", "") in raw_answer.lower().replace(" ", "")):
                        cited_ids.append(doc.id)
                    elif doc.id == "IN-PAT-SEC-003P" and ("3(p)" in raw_answer.lower() or "traditional knowledge" in raw_answer.lower()):
                        cited_ids.append(doc.id)
                    elif doc.id == "IN-PAT-SEC-003E" and ("3(e)" in raw_answer.lower() or "mere admixture" in raw_answer.lower()):
                        cited_ids.append(doc.id)
                    elif doc.id == "IN-PAT-SEC-039" and ("section 39" in raw_answer.lower() or "foreign filing" in raw_answer.lower()):
                        cited_ids.append(doc.id)
                    elif doc.id == "IN-TKDL-ACC-AGREE" and "tkdl" in raw_answer.lower():
                        cited_ids.append(doc.id)
                    elif doc.id == "INT-WIPO-GRATK-2024" and ("gratk" in raw_answer.lower() or "genetic resources" in raw_answer.lower()):
                        cited_ids.append(doc.id)
                    elif doc.id == "IN-CASE-TURMERIC-CSIR" and ("turmeric" in raw_answer.lower() and "csir" in raw_answer.lower()):
                        cited_ids.append(doc.id)

        verified_ids = [c for c in cited_ids if c in doc_map and corpus_store.get_by_id(c)]
        unverified_ids = [c for c in cited_ids if c not in verified_ids]

        validated_citations: List[CitationItem] = []
        if not model_abstained:
            for doc in retrieved_docs:
                if doc.id in verified_ids:
                    cd = corpus_store.get_by_id(doc.id)
                    validated_citations.append(CitationItem(
                        id=doc.id, jurisdiction=doc.jurisdiction, statute=doc.statute,
                        section_rule=doc.section_rule, authority=doc.authority,
                        official_url=doc.official_url, title=doc.title,
                        relevance_score=doc.score,
                        verification_status=(cd.verification_status or ("verified " + cd.last_verified)) if cd.last_verified or cd.verification_status else None,
                        last_verified=cd.last_verified,
                        cited_in_answer=True))

        if model_abstained:
            citation_check = "abstained"
        elif validated_citations and not unverified_ids:
            citation_check = "all_verified"
        elif validated_citations:
            citation_check = "partially_verified"
        else:
            citation_check = "no_verified_citations"

        # Step 6: Confidence from verified citations + retrieval score (not model self-report)
        if model_abstained or citation_check == "no_verified_citations":
            confidence, is_abstained = "Low", model_abstained
        elif top_score >= 0.65 and len(validated_citations) >= 2 and citation_check == "all_verified" and retrieval_mode == "dense":
            confidence, is_abstained = "High", False
        else:
            confidence, is_abstained = "Medium", False

        n_unver = sum(1 for c in validated_citations if not c.last_verified)
        confidence_reason = (
            f"Top retrieval score {top_score:.2f} ({retrieval_mode} retrieval); "
            f"{len(validated_citations)} citation(s) checked against the corpus ({citation_check.replace('_', ' ')}); "
            f"{n_unver} cited source(s) are curated summaries not yet manually verified against the official text."
        )
        if model_abstained:
            confidence_reason = "The model found the retrieved provisions insufficient and abstained."
        elif retrieval_mode != "dense" and confidence == "Medium":
            confidence_reason += " Keyword fallback was used, so confidence is capped at Medium."

        if citation_check == "no_verified_citations" and not model_abstained:
            raw_answer += "\n\n[SAKTI notice: this answer did not cite any retrieved source ID, so it could not be verified. Treat it as unverified.]"
        if unverified_ids:
            raw_answer += "\n\n[SAKTI notice: the answer referenced unknown source IDs (" + ", ".join(unverified_ids) + ") which were removed from the citation list.]"

        return SynthesisResponse(
            query=query,
            jurisdiction=jurisdiction or "All",
            answer=raw_answer,
            confidence=confidence,
            is_abstained=is_abstained,
            citations=validated_citations,
            disclaimer=disclaimer_text,
            language=extra_lang or target_lang,
            retrieval_mode=retrieval_mode,
            citation_check=citation_check,
            unverified_citation_ids=unverified_ids,
            generation_mode=generation_mode,
            confidence_reason=confidence_reason
        )

    def synthesize(self, query: str, jurisdiction: Optional[str] = "India", top_k: int = 4, language: Optional[str] = "en") -> SynthesisResponse:
        """Public entry point: runs synthesis and writes an audit record."""
        t0 = time.time()
        resp = self._synthesize(query, jurisdiction, top_k, language)
        log_event(
            "query", query=query, jurisdiction=resp.jurisdiction, language=resp.language,
            retrieval_mode=resp.retrieval_mode, generation_mode=resp.generation_mode, model=self.last_model,
            confidence=resp.confidence, abstained=resp.is_abstained, citation_check=resp.citation_check,
            cited_ids=[c.id for c in resp.citations], unverified_ids=resp.unverified_citation_ids,
            top_scores=[round(c.relevance_score, 3) for c in resp.citations][:4],
            latency_ms=int((time.time() - t0) * 1000))
        return resp

synthesizer = GroundedSynthesizer()
